config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin/home#index'

  namespace :admin, path: '/admin' do
    root 'home#index'
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :message, presence: true

  enum role: {
    client: 0,
    manager: 1
  }

  before_create :generate_account

  def generate_account
    self.account = (SecureRandom.random_number * (10**6)).round.to_s
    generate_account if User.exists?(account: self.account)
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    before_action :authenticate_user!
    layout 'admin'
  end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  class HomeController < BaseController
    def index; end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    def index
      @users = User.client.all
    end

    def show
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = 'Cliente atualizado com sucesso!'
        redirect_to admin_users_path
      else
        flash[:alert] = 'Algo deu errado ao criar usuário.'
        render :new
      end
    end

    def edit
    end

    def update
      if @user.update(user_params)
        flash[:notice] = 'Cliente atualizado com sucesso!'
        redirect_to admin_users_path
      else
        flash[:alert] = 'Algo deu errado ao atualizar usuário.'
        render :edit
      end
    end

    def destroy
      if current_user.id != @user.id
        message = 'Cliente excluído com sucesso!'
        @user.destroy
      else
        message = 'Você não pode excluir a sua própria conta.'
      end
      flash[:notice] = message
      redirect_to action: :index
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :message)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  def after_sign_in_path_for(resource_or_scope)
    if current_user.client?
      sign_out(current_user)
      root_path
    else
      admin_root_path || stored_location_for(resource_or_scope)
    end
  end

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <%= render partial: 'shared/admin/page_title', locals: { title: 'Bem vindo ao CashWay' } %>

  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6">
          <div class="card">
            <div class="card-header">
              <h5 class="m-0">Total de clientes</h5>
            </div>
            <div class="card-body">
              <h6 class="card-title">Quantidade de clientes ativos: <%= User.client.count %></h6>

              <br />
              <a href="<%= admin_users_url %>" class="btn btn-primary">Ir para clientes</a>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
  <%= f.input :name %>
  <%= f.input :email, required: true %>
  <% if @user.new_record? %>
    <%= f.input :password, required: true %>
    <%= f.input :password_confirmation, required: true %>
  <% end %>
  <%= f.input :message %>
  <%= f.button :submit, 'Salvar', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="content-wrapper">
  <%= render partial: 'shared/admin/page_title', locals: { title: 'Cliente' } %>

  <div class="content">
    <div class="container-fluid">
      <div class="row">
        
        <div class="col-lg-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h5 class="m-0">Editar</h5>
            </div>
            <div class="card-body">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <%= render partial: 'shared/admin/page_title', locals: { title: 'Clientes' } %>

  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        
        <div class="col-lg-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h5 class="m-0">Listagem</h5>
            </div>
            <div class="card-body">
              <% if @users.any? %>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col"><%= I18n.t('activerecord.attributes.user.name') %></th>
                      <th scope="col"><%= I18n.t('activerecord.attributes.user.email') %></th>
                      <th scope="col"><%= I18n.t('activerecord.attributes.user.account') %></th>
                      <th scope="col"><%= I18n.t('activerecord.attributes.user.created_at') %></th>
                      <th scope="col">Ações</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <th scope="row"><%= user.id %></th>
                        <td><%= user.name %></td>
                        <td><%= user.email %></td>
                        <td><%= user.account %></td>
                        <td><%= l user.created_at, format: :short %></td>
                        <td>
                          <%= link_to 'Detalhes', admin_user_path(user), class: 'btn btn-warning' %>
                          <%= link_to 'Editar', edit_admin_user_path(user), class: 'btn btn-primary' %>
                          <%= link_to 'Excluir', admin_user_path(user), method: :delete, class: 'btn btn-danger', data: { confirm: 'Deseja realmente excluir?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              <% else %>
                <p>Nenhum cliente cadastrado</p>
              <% end %>

              <%= link_to 'Novo', new_admin_user_path, class: 'btn btn-primary'%>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/admin/users/new.html.erb
<div class="content-wrapper">
  <%= render partial: 'shared/admin/page_title', locals: { title: 'Cliente' } %>

  <div class="content">
    <div class="container-fluid">
      <div class="row">
        
        <div class="col-lg-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h5 class="m-0">Novo</h5>
            </div>
            <div class="card-body">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="content-wrapper">
  <%= render partial: 'shared/admin/page_title', locals: { title: 'Cliente' } %>

  <div class="content">
    <div class="container-fluid">
      <div class="row">
        
        <div class="col-lg-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h5 class="m-0">Detalhes</h5>
            </div>
            <div class="card-body">
              <p>
                <strong><%= I18n.t('activerecord.attributes.user.name') %>:</strong>
                <%= @user.name %>
              </p>
              <p>
                <strong><%= I18n.t('activerecord.attributes.user.email') %>:</strong>
                <%= @user.email %>
              </p>
              <p>
                <strong><%= I18n.t('activerecord.attributes.user.account') %>:</strong>
                <%= @user.account %>
              </p>
              <p>
                <strong><%= I18n.t('activerecord.attributes.user.created_at') %>:</strong>
                <%= l @user.created_at, format: :short %>
              </p>
<p>
                <strong><%= I18n.t('activerecord.attributes.user.message') %>:</strong>
                <%= @user.message %>
              </p>

              <%= link_to 'Voltar', admin_users_path, class: 'btn btn-primary'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Carousel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Launch static backdrop modal
        </button>

        <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">
          Tooltip on top
        </button>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                ...
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerencial - CashWay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
  </head>

  <body class='hold-transition sidebar-mini'>
    <div class="wrapper">
      <!-- Navbar -->
      <%= render 'shared/admin/navbar'%>
      <!-- Aside -->
      <%= render 'shared/admin/aside'%>

      <%= yield %>

      <!-- Control Sidebar -->
      <%= render 'shared/admin/right_sidebar' %>
      <!-- Main Footer -->
      <%= render 'shared/admin/footer' %>
      <%= render 'shared/admin/alert' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerencial - CashWay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'devise', media: 'all' %>
    <%= javascript_include_tag 'devise' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
  </head>

  <body>
    <div id="logreg-forms">
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/admin/_alert.html.erb
<% if flash[:notice].present? %>
  <script>
    let notify = new ToastrNotify('Aviso', 'Tudo certo!', "<%= flash[:notice] %>");
    $(document).Toasts('create', notify.alert('bg-success'));
  </script>
<% end %>
<% if flash[:error].present? %>
  <script>
    let notify = new ToastrNotify('Erro', 'Algo deu errado!', "<%= flash[:error] %>");
    $(document).Toasts('create', notify.alert('bg-danger'));
  </script>
<% end %>
<% flash.discard %>

app/views/shared/admin/_aside.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <%= image_tag 'AdminLTELogo.png', class: 'brand-image img-circle elevation-3', alt: 'Logo System' %>
    <!-- <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
    <span class="brand-text font-weight-light">Challenge CashWay</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <%= image_tag 'user2-160x160.jpg', class: 'img-circle elevation-2', alt: 'User Image' %>
        <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> -->
      </div>
      <div class="info">
        <a href="#" class="d-block"><%= current_user.name %></a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <a href="<%= admin_users_url %>" class="nav-link">
            <i class="nav-icon fas fa-users"></i>
            <p>
              Clientes
            </p>
          </a>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, :method => :delete, class: 'nav-link' do %>
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
              Sair
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/shared/admin/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; <%= Time.new.year %> <%= link_to 'Challenge CashWay', admin_root_url %>.</strong> All rights reserved.
</footer>

app/views/shared/admin/_navbar.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to 'Home', admin_root_url, class: 'nav-link' %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to 'Clientes', admin_users_url, class: 'nav-link' %>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/shared/admin/_page_title.html.erb
<!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0"><%= title %></h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active"><%= title %></li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

app/views/shared/admin/_right_sidebar.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <h5>Title</h5>
    <p>Sidebar content</p>
  </div>
</aside>
<!-- /.control-sidebar -->